# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

namespace: default

config:
  LLM_MODEL_ID: meta-llama/Meta-Llama-3-8B-Instruct
  CONFIG_MAP_NAME: visualqna-config
  NODE_SELECTOR: opea
  HUGGINGFACEHUB_API_TOKEN: ${HF_TOKEN}

  LVM_ENDPOINT: "http://visualqna-tgi"
  MODEL_ID: "llava-hf/llava-v1.6-mistral-7b-hf"
  LVM_SERVICE_HOST_IP: visualqna-lvm-uservice
  PORT: "8399"
  MAX_INPUT_TOKENS: "4096"
  MAX_TOTAL_TOKENS: "8192"

microservices:
  - name: visualqna-lvm-uservice
    image: opea/lvm-tgi:latest
    replicas: 1
    ports:
      - containerPort: 9399

  - name: visualqna
    image: opea/visualqna:latest
    replicas: 1
    ports:
      - containerPort: 8399

  - name: visualqna-tgi
    image: ghcr.io/huggingface/tgi-gaudi:2.0.5
    replicas: 1
    ports:
      - containerPort: 8399
    resources:
      limits:
        habana.ai/gaudi: 1
    volumeMounts:
      - mountPath: /data
        name: model-volume
      - mountPath: /dev/shm
        name: shm
    volumes:
      - hostPath:
          path: /mnt/models
          type: Directory
        name: model-volume
      - emptyDir:
          medium: Memory
          sizeLimit: 1Gi
        name: shm

services:
  - name: visualqna-lvm-uservice
    spec:
      ports:
        - name: service
          port: 9399
          targetPort: 9399
      selector:
        app: visualqna-lvm-uservice
      type: ClusterIP

  - name: visualqna-tgi
    spec:
      ports:
        - name: service
          port: 80
          targetPort: 8399
      selector:
        app: lvm-uservice
      type: ClusterIP

  - name: visualqna
    spec:
      ports:
        - name: service
          port: 8888
          targetPort: 8888
      selector:
        app: visualqna
      type: ClusterIP
