# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.CONFIG_MAP_NAME }}
  namespace: default
data:
  HUGGINGFACEHUB_API_TOKEN: {{ .Values.HUGGINGFACEHUB_API_TOKEN }}
  LLM_MODEL_ID: {{ .Values.config.LLM_MODEL_ID }}
  NODE_SELECTOR: {{ .Values.config.NODE_SELECTOR }}

  CONFIG_MAP_NAME: visualqna-config
  NODE_SELECTOR: opea
  HUGGINGFACEHUB_API_TOKEN: ${HF_TOKEN}

  LVM_ENDPOINT: "http://visualqna-tgi"
  MODEL_ID: "llava-hf/llava-v1.6-mistral-7b-hf"
  LVM_SERVICE_HOST_IP: visualqna-lvm-uservice
  PORT: "8399"
  MAX_INPUT_TOKENS: "4096"
  MAX_TOTAL_TOKENS: "8192"
---
